// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-gateway/internal/app/gateway/biz"
	auth2 "github.com/go-gateway/internal/app/gateway/data/auth"
	"github.com/go-gateway/internal/app/gateway/service/auth"
	"github.com/go-gateway/internal/pkg/router/svc"
)

// Injectors from wire.go:

func InitRouterService() *svc.RouterService {
	authService := auth.NewAuthService()
	authRepo := auth2.NewAuthURLRepo()
	bizAuthService := biz.NewBizUserService(authRepo)
	tokenService := auth.NewTokenService(bizAuthService)
	routerService := svc.NewRouterService(authService, tokenService)
	return routerService
}
