// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-gateway/internal/app/gateway/service/auth"
	"github.com/go-gateway/internal/pkg/router/model"
)

// Injectors from wire.go:

func InitRouterService() *model.RouterService {
	authService := auth.NewAuthService()
	tokenService := auth.NewTokenService()
	routerService := model.NewRouterService(authService, tokenService)
	return routerService
}
