// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/xiaozefeng/go-gateway/internal/gateway/biz"
	"github.com/xiaozefeng/go-gateway/internal/gateway/data/auth"
	"github.com/xiaozefeng/go-gateway/internal/gateway/data/db"
	"github.com/xiaozefeng/go-gateway/internal/gateway/server"
	"github.com/xiaozefeng/go-gateway/internal/pkg/thirdparty/eureka"
	"github.com/xiaozefeng/go-gateway/internal/pkg/thirdparty/member"
)

// Injectors from wire.go:

func InitRouterService(eurekaServerURL eureka.ServerURL, mysqlConnectURL db.MySQLConnectURL) (*server.RouterService, func(), error) {
	sqlDB, cleanup, err := db.New(mysqlConnectURL)
	if err != nil {
		return nil, nil, err
	}
	authRepo := auth.NewURLRepo(sqlDB)
	client := eureka.NewClient(eurekaServerURL)
	authUserCase := biz.NewAuthUserCase(authRepo, client)
	memberService := member.NewUserCase(client)
	tokenUserCase := biz.NewTokenUserCase(authUserCase, client, memberService)
	routerService := server.NewRouterService(authUserCase, tokenUserCase)
	return routerService, func() {
		cleanup()
	}, nil
}
