// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/xiaozefeng/go-gateway/internal/gateway/api/svc"
	"github.com/xiaozefeng/go-gateway/internal/gateway/biz"
	auth2 "github.com/xiaozefeng/go-gateway/internal/gateway/data/auth"
	"github.com/xiaozefeng/go-gateway/internal/gateway/service/auth"
)

// Injectors from wire.go:

func InitRouterService() *svc.RouterService {
	authService := auth.NewAuthService()
	authURLRepo := auth2.NewAuthURLRepo()
	authUsercase := biz.NewBizUserService(authURLRepo)
	tokenService := auth.NewTokenService(authUsercase)
	routerService := svc.NewRouterService(authService, tokenService)
	return routerService
}
