// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/xiaozefeng/go-gateway/internal/gateway/api/svc"
	"github.com/xiaozefeng/go-gateway/internal/gateway/biz"
	auth2 "github.com/xiaozefeng/go-gateway/internal/gateway/data/auth"
	"github.com/xiaozefeng/go-gateway/internal/gateway/data/db"
	"github.com/xiaozefeng/go-gateway/internal/gateway/service/auth"
	"github.com/xiaozefeng/go-gateway/internal/pkg/client/eureka"
	"github.com/xiaozefeng/go-gateway/internal/pkg/client/member"
)

// Injectors from wire.go:

func InitRouterService(eurekaServerURL string, db *sql.DB) *svc.RouterService {
	client := InitEurekaClient(eurekaServerURL)
	authService := auth.NewAuthService(client)
	authURLRepo := auth2.NewAuthURLRepo(db)
	authUsercase := biz.NewBizUserService(authURLRepo)
	memberService := member.NewMemberService(client)
	tokenService := auth.NewTokenService(authUsercase, client, memberService)
	routerService := svc.NewRouterService(authService, tokenService)
	return routerService
}

func InitEurekaClient(eurekaServerURL string) *eureka.Client {
	client := eureka.NewClient(eurekaServerURL)
	return client
}

func InitDB() (*sql.DB, error) {
	sqlDB, err := db.Init()
	if err != nil {
		return nil, err
	}
	return sqlDB, nil
}
